<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GenericVectorBuilder.Core\GenericVectorBuilder.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DuckDB.NET.Data.Full" Version="1.5.6" />
    <PackageReference Include="MongoDB.Driver" Version="3.12.0" />
    <PackageReference Include="MySqlConnector" Version="2.6.2" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="NRedisStack" Version="1.8.0" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.301" />
    <PackageReference Include="Pgvector" Version="0.3.2" />
    <PackageReference Include="sqlite-vec" Version="0.1.7-alpha.2.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
